using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Fractal : MonoBehaviour
{
    /// <summary>
    /// a Mesh is a construct used by the graphics hardware to draw complex stuff. 
    /// It's a 3D object that's either imported into Unity, one of Unity's default shapes, or generated by code.
    /// </summary>
    public Mesh Mesh;

    /// <summary>
    /// Materials are used to define the visual properties of objects. 
    /// They can range from very simple, like a constant color, to very complex.
    /// </summary>
    public Material Material;

    /// <summary>
    /// To control the maximum amount of GameObject instantiated for the Fractal,
    /// we use this property
    /// </summary>
    public int MaxDepth;
        
    public float ChildScale;

    private int _depth;


    // Start is called before the first frame update
    void Start()
    {
        // The AddComponent method creates a new component of a certain type, 
        // attaches it to the game object, and returns a reference to it.
        gameObject.AddComponent<MeshFilter>().mesh = this.Mesh;
        gameObject.AddComponent<MeshRenderer>().material = this.Material;

        if(this._depth < MaxDepth)
        {
            new GameObject("Fractal Child")
                .AddComponent<Fractal>()
                .InitializeChild(this);
        }
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    /// <summary>
    /// To control the amount of Fractals instantiated, we need to copy
    /// some values from the parent and increase the depth
    /// </summary>
    /// <param name="parent">GameObject to add a new Fractal child to</param>
    private void InitializeChild(Fractal parent)
    {
        this.Mesh = parent.Mesh;
        this.Material = parent.Material;
        this.MaxDepth = parent.MaxDepth;
        this.ChildScale = parent.ChildScale;
        this._depth = parent._depth + 1;

        // The parent–child relationship between game objects is 
        // defined by their transformation hierarchy.
        this.transform.parent = parent.transform;

        this.transform.localScale = Vector3.one * this.ChildScale;

        this.transform.localPosition = Vector3.up * (0.5f + 0.5f * this.ChildScale);
    }
}
